Updates from last review
subvisual/alchemyconf.com pull request #32
Opened 2021-04-13 15:16 UTC by PedroBailaAndrade

- white space on hero image gone;
<img width="944" alt="Captura de ecrã 2021-04-13, às 14 27 23" src="https://user-images.githubusercontent.com/52913878/114576597-2fad7100-9c73-11eb-98b8-c58464f5a93c.png">

- naming of Speakers section inside schedule page section changed;
- redundant utility deleted;
- nav element updated so it doesn’t have additional div;

2021-04-13 15:45 UTC, joaojusto requested changes

2021-04-13 15:45 UTC, joaojusto commented on priv/site/schedule.slime
> +  /           span 2021
Please delete commented code

2021-04-13 15:45 UTC, joaojusto commented on priv/site/_includes/css/components/Schedule.scss
> +}
Why is this here?

2021-04-15 11:26 UTC, joaojusto requested changes
This is good to go, we just need to fix the casing on some classes and the new lines at end of files.

2021-04-15 11:26 UTC, joaojusto commented on priv/site/_includes/css/components/Schedule.scss
> +.scheduleSpeakers-contentTalkTitle {
I think this should be CamelCase, `ScheduleSpeakers-contentTalkTitle`.

2021-04-15 11:26 UTC, joaojusto commented on priv/site/_includes/css/components/MobileNav.scss
> +}
Missing new line at end of file, you should take a look at your editor preferences, most likely you have the option to auto add the new line off.

2021-04-15 11:26 UTC, joaojusto commented on priv/site/_includes/css/components/MobileNav.scss
Can we get rid of the empty lines here?

2021-04-15 11:26 UTC, joaojusto commented on priv/site/_includes/schedule/nav.slime
> += include(@env, "_includes/mobile_nav.slime")
Again, missing new line at end of file

2021-04-15 11:26 UTC, joaojusto commented on priv/site/schedule.slime
> +  /           span 2021
Please don't forget to remove the commented code

2021-04-15 11:43 UTC, PedroBailaAndrade commented on priv/site/_includes/css/components/MobileNav.scss
I don't have that line.

2021-04-15 12:01 UTC, joaojusto approved these changes
LGTM 🚢 :shipit:

2021-04-15 12:05 UTC, merged